NASA_PRODUCTS = [
    {
        "id": "apod",
        "name": "APOD",
        "description": "Imagem ou video astronomico selecionado para o dia.",
        "route": "/api/v1/apod",
        "example": "/api/v1/apod?thumbs=true",
        "featured": True,
    },
    {
        "id": "asteroids",
        "name": "Asteroids NeoWs",
        "description": "Aproximacoes de objetos proximos da Terra.",
        "route": "/api/v1/asteroids",
        "example": "/api/v1/asteroids/browse?page=0&size=12",
        "featured": True,
    },
    {
        "id": "donki",
        "name": "DONKI",
        "description": "Eventos de clima espacial e suas analises.",
        "route": "/api/v1/donki",
        "example": "/api/v1/donki/notifications?type=all",
        "featured": True,
    },
    {
        "id": "eonet",
        "name": "EONET",
        "description": "Eventos naturais observados na Terra.",
        "route": "/api/v1/eonet",
        "example": "/api/v1/eonet/events?status=open&limit=10",
        "featured": True,
    },
    {
        "id": "epic",
        "name": "EPIC",
        "description": "Imagens policromaticas da Terra obtidas pelo DSCOVR.",
        "route": "/api/v1/epic",
        "example": "/api/v1/epic/natural",
        "featured": True,
    },
    {
        "id": "exoplanets",
        "name": "Exoplanet Archive",
        "description": "Consultas TAP ao arquivo de exoplanetas confirmados.",
        "route": "/api/v1/exoplanets",
        "example": "/api/v1/exoplanets/query?query=select+top+10+*+from+ps",
        "featured": False,
    },
    {
        "id": "gibs",
        "name": "GIBS",
        "description": "Camadas globais de imagens de satelite.",
        "route": "/api/v1/gibs",
        "example": "/api/v1/gibs/capabilities",
        "featured": False,
    },
    {
        "id": "insight",
        "name": "InSight",
        "description": "Dados meteorologicos historicos da missao InSight.",
        "route": "/api/v1/insight",
        "example": "/api/v1/insight?feedtype=json&ver=1.0",
        "featured": False,
    },
    {
        "id": "images",
        "name": "NASA Image and Video Library",
        "description": "Pesquisa de imagens, videos e audios da NASA.",
        "route": "/api/v1/images",
        "example": "/api/v1/images/search?q=artemis&media_type=image",
        "featured": True,
    },
    {
        "id": "osdr",
        "name": "Open Science Data Repository",
        "description": "Dados biologicos de experimentos espaciais.",
        "route": "/api/v1/osdr",
        "example": "/api/v1/osdr/search?term=spaceflight",
        "featured": False,
    },
    {
        "id": "ssc",
        "name": "Satellite Situation Center",
        "description": "Localizacoes e trajetorias de naves espaciais.",
        "route": "/api/v1/ssc",
        "example": "/api/v1/ssc/observatories",
        "featured": False,
    },
    {
        "id": "ssd",
        "name": "SSD/CNEOS",
        "description": "Servicos do sistema solar e objetos proximos da Terra.",
        "route": "/api/v1/ssd",
        "example": "/api/v1/ssd/fireball?limit=10",
        "featured": False,
    },
    {
        "id": "techport",
        "name": "TechPort",
        "description": "Portfolio de investimentos em tecnologia da NASA.",
        "route": "/api/v1/techport",
        "example": "/api/v1/techport/projects",
        "featured": False,
    },
    {
        "id": "techtransfer",
        "name": "TechTransfer",
        "description": "Patentes, software e tecnologias disponiveis.",
        "route": "/api/v1/techtransfer",
        "example": "/api/v1/techtransfer/patent?query=robotics",
        "featured": False,
    },
    {
        "id": "tle",
        "name": "TLE API",
        "description": "Elementos orbitais de satelites e objetos espaciais.",
        "route": "/api/v1/tle",
        "example": "/api/v1/tle?search=ISS",
        "featured": False,
    },
    {
        "id": "trek",
        "name": "NASA Trek WMTS",
        "description": "Mapas em mosaico de Marte, Lua e Vesta.",
        "route": "/api/v1/trek",
        "example": (
            "/api/v1/trek/mars/capabilities"
            "?mosaic=Mars_Viking_MDIM21_ClrMosaic_global_232m"
        ),
        "featured": False,
    },
]
